export { default as Navbar } from "./Navbar/Navbar";
export { default as Hero } from "./Hero/Hero";
export { default as Footer } from "./Footer/Footer";
export { default as Buckets } from "./Buckets/Buckets";
export { default as InfoSection } from "./InfoSection/InfoSection";
export { default as InNumbers } from "./InNumbers/InNumbers";
export { default as SectionHeader } from "./SectionHeader/SectionHeader";
export { default as PageTitle } from "./PageTitle/PageTitle";
export { default as Card } from "./Card/Card";
